# ~/Library/Application Support/lazygit/config.yml

gui:
  theme:
    lightTheme: false
    activeBorderColor: ["#FFD700", "bold"] # Gold
    inactiveBorderColor: ["#6272A4"] # Muted blue
    selectedLineBgColor: ["#44475A"] # Darker selection
    optionsTextColor: ["#8BE9FD"] # Cyan
    searchingActiveBorderColor: ["#50FA7B"] # Green when searching
    cherryPickedCommitBgColor: ["#BD93F9"] # Purple
    cherryPickedCommitFgColor: ["#282A36"] # Dark foreground
    unstagedChangesColor: ["#FF5555"] # Red
    defaultFgColor: ["#F8F8F2"] # Light foreground
  nerdFontsVersion: "3"
  showIcons: true
  showFileTree: true
  showListFooter: true
  showRandomTip: false
  showCommandLog: true
  commandLogSize: 8
  splitDiff: "auto"
  scrollHeight: 2
  scrollPastBottom: true
  mouseEvents: true
  skipDiscardChangeWarning: false
  skipStashWarning: false
  sidePanelWidth: 0.3333
  expandFocusedSidePanel: false
  mainPanelSplitMode: "flexible"
  enlargedSideViewLocation: "left"
  border: "rounded"
  # Author coloring
  authorColors:
    "*": "#FF79C6"
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
  commit:
    signOff: false
    autoWrapCommitMessage: true
    autoWrapWidth: 72
  merging:
    manualCommit: false
    args: ""
  mainBranches: ["master", "main", "develop"]
  skipHookPrefix: "WIP"
  autoFetch: true
  autoRefresh: true
  fetchAll: true
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"
  overrideGpg: false
  disableForcePushing: false
  parseEmoji: true
  diffContextSize: 3
  allBranchesLogCmds:
    - git log --graph --all --color=always --abbrev-commit --decorate --date=relative --pretty=medium
os:
  editPreset: "nvim"
  openCommand: "open {{filename}}"
keybinding:
  universal:
    quit: "q"
    quit-alt1: "<c-c>"
    return: "<esc>"
    quitWithoutChangingDirectory: "Q"
    togglePanel: "<tab>"
    prevItem: "<up>"
    nextItem: "<down>"
    prevItem-alt: "k"
    nextItem-alt: "j"
    prevPage: ","
    nextPage: "."
    gotoTop: "<"
    gotoBottom: ">"
    scrollLeft: "H"
    scrollRight: "L"
    prevBlock: "<left>"
    nextBlock: "<right>"
    prevBlock-alt: "h"
    nextBlock-alt: "l"
    jumpToBlock: ["1", "2", "3", "4", "5"]
    nextMatch: "n"
    prevMatch: "N"
    optionMenu: "<disabled>"
    optionMenu-alt1: "?"
    select: "<space>"
    goInto: "<enter>"
    openRecentRepos: "<c-r>"
    confirm: "<enter>"
    remove: "d"
    new: "n"
    edit: "e"
    openFile: "o"
    scrollUpMain: "<pgup>"
    scrollDownMain: "<pgdown>"
    scrollUpMain-alt1: "K"
    scrollDownMain-alt1: "J"
    scrollUpMain-alt2: "<c-u>"
    scrollDownMain-alt2: "<c-d>"
    executeShellCommand: ":"
    createRebaseOptionsMenu: "m"
    pushFiles: "P"
    pullFiles: "p"
    refresh: "R"
    createPatchOptionsMenu: "<c-p>"
    nextTab: "]"
    prevTab: "["
    nextScreenMode: "+"
    prevScreenMode: "_"
    undo: "z"
    redo: "<c-z>"
    filteringMenu: "<c-s>"
    diffingMenu: "W"
    diffingMenu-alt: "<c-e>"
    copyToClipboard: "<c-o>"
    submitEditorText: "<enter>"
    extrasMenu: "@"
    toggleWhitespaceInDiffView: "<c-w>"
    increaseContextInDiffView: "}"
    decreaseContextInDiffView: "{"
    openDiffTool: "<c-t>"
  status:
    checkForUpdate: "u"
    recentRepos: "<enter>"
  files:
    commitChanges: "c"
    commitChangesWithoutHook: "w"
    amendLastCommit: "A"
    commitChangesWithEditor: "C"
    confirmDiscard: "x"
    ignoreFile: "i"
    refreshFiles: "r"
    stashAllChanges: "s"
    viewStashOptions: "S"
    toggleStagedAll: "a"
    viewResetOptions: "D"
    fetch: "f"
    toggleTreeView: "`"
    openMergeOptions: "M"
    openStatusFilter: "<c-b>"
    copyFileInfoToClipboard: "y"
  branches:
    createPullRequest: "o"
    viewPullRequestOptions: "O"
    checkoutBranchByName: "c"
    forceCheckoutBranch: "F"
    rebaseBranch: "r"
    renameBranch: "R"
    mergeIntoCurrentBranch: "M"
    viewGitFlowOptions: "i"
    fastForward: "f"
    createTag: "T"
    pushTag: "P"
    setUpstream: "u"
    fetchRemote: "f"
    sortOrder: "s"
  commits:
    squashDown: "s"
    renameCommit: "r"
    renameCommitWithEditor: "R"
    viewResetOptions: "g"
    markCommitAsFixup: "f"
    createFixupCommit: "F"
    squashAboveCommits: "S"
    moveDownCommit: "<c-j>"
    moveUpCommit: "<c-k>"
    amendToCommit: "A"
    pickCommit: "p"
    revertCommit: "t"
    cherryPickCopy: "C"
    pasteCommits: "V"
    markCommitAsBaseForRebase: "B"
    tagCommit: "T"
    checkoutCommit: "<space>"
    resetCherryPick: "<c-R>"
    copyCommitAttributeToClipboard: "y"
    openLogMenu: "<c-l>"
    openInBrowser: "o"
    viewBisectOptions: "b"
    startInteractiveRebase: "i"
  stash:
    popStash: "g"
    renameStash: "r"
  commitFiles:
    checkoutCommitFile: "c"
  main:
    toggleSelectHunk: "a"
    pickBothHunks: "b"
  submodules:
    init: "i"
    update: "u"
    bulkMenu: "b"
  worktrees:
    viewWorktreeOptions: "w"
disableStartupPopups: true
confirmOnQuit: false
quitOnTopLevelReturn: true
# Filter mode
promptToReturnFromSubprocess: true
# Custom commands
customCommands:
  - key: "<c-f>"
    command: "git fetch --all --prune"
    context: "global"
    description: "Fetch all remotes"
    loadingText: "Fetching..."
  - key: "b"
    command: "git branch --sort=-committerdate | head -20"
    context: "localBranches"
    description: "Recent branches"
    output: terminal
